# Generated by Django 5.1.2 on 2024-12-17 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_comment_parent_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
